<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ec extends \App\Entity\Ec implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'ue', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'coeff', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'cours', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'prof', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'reactions', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'statusEcs', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'bibliotheques'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'ue', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'coeff', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'cours', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'prof', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'reactions', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'statusEcs', '' . "\0" . 'App\\Entity\\Ec' . "\0" . 'bibliotheques'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ec $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUe(): ?\App\Entity\Ue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUe', []);

        return parent::getUe();
    }

    /**
     * {@inheritDoc}
     */
    public function setUe(?\App\Entity\Ue $ue): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUe', [$ue]);

        return parent::setUe($ue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoeff(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoeff', []);

        return parent::getCoeff();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoeff(int $coeff): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoeff', [$coeff]);

        return parent::setCoeff($coeff);
    }

    /**
     * {@inheritDoc}
     */
    public function getCours(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCours', []);

        return parent::getCours();
    }

    /**
     * {@inheritDoc}
     */
    public function addCour(\App\Entity\Cours $cour): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCour', [$cour]);

        return parent::addCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCour(\App\Entity\Cours $cour): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCour', [$cour]);

        return parent::removeCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function getProf(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProf', []);

        return parent::getProf();
    }

    /**
     * {@inheritDoc}
     */
    public function setProf(?\App\Entity\User $prof): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProf', [$prof]);

        return parent::setProf($prof);
    }

    /**
     * {@inheritDoc}
     */
    public function getReactions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReactions', []);

        return parent::getReactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addReaction(\App\Entity\Reaction $reaction): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReaction', [$reaction]);

        return parent::addReaction($reaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReaction(\App\Entity\Reaction $reaction): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReaction', [$reaction]);

        return parent::removeReaction($reaction);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusEcs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusEcs', []);

        return parent::getStatusEcs();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatusEc(\App\Entity\StatusEc $statusEc): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatusEc', [$statusEc]);

        return parent::addStatusEc($statusEc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatusEc(\App\Entity\StatusEc $statusEc): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatusEc', [$statusEc]);

        return parent::removeStatusEc($statusEc);
    }

    /**
     * {@inheritDoc}
     */
    public function getBibliotheques(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBibliotheques', []);

        return parent::getBibliotheques();
    }

    /**
     * {@inheritDoc}
     */
    public function addBibliotheque(\App\Entity\Bibliotheque $bibliotheque): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBibliotheque', [$bibliotheque]);

        return parent::addBibliotheque($bibliotheque);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBibliotheque(\App\Entity\Bibliotheque $bibliotheque): \App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBibliotheque', [$bibliotheque]);

        return parent::removeBibliotheque($bibliotheque);
    }

}
