<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Code extends \App\Entity\Code implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'icon', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'fichierIcon', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'mentions', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'parcours'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'icon', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'fichierIcon', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'mentions', '' . "\0" . 'App\\Entity\\Code' . "\0" . 'parcours'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Code $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Code
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMentions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMentions', []);

        return parent::getMentions();
    }

    /**
     * {@inheritDoc}
     */
    public function addMention(\App\Entity\Mention $mention): \App\Entity\Code
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMention', [$mention]);

        return parent::addMention($mention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMention(\App\Entity\Mention $mention): \App\Entity\Code
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMention', [$mention]);

        return parent::removeMention($mention);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getParcours(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcours', []);

        return parent::getParcours();
    }

    /**
     * {@inheritDoc}
     */
    public function addParcour(\App\Entity\Parcours $parcour): \App\Entity\Code
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParcour', [$parcour]);

        return parent::addParcour($parcour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParcour(\App\Entity\Parcours $parcour): \App\Entity\Code
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParcour', [$parcour]);

        return parent::removeParcour($parcour);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcon', []);

        return parent::getIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcon($icon): \App\Entity\Code
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcon', [$icon]);

        return parent::setIcon($icon);
    }

    /**
     * {@inheritDoc}
     */
    public function setFichierIcon(\Symfony\Component\HttpFoundation\File\File $fichierIcon = NULL): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichierIcon', [$fichierIcon]);

        parent::setFichierIcon($fichierIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichierIcon(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichierIcon', []);

        return parent::getFichierIcon();
    }

}
