<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \App\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'ec', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichierSupport', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'audio', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'video', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'livre', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichierlivre', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichier', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichiercour'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'ec', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichierSupport', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'audio', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'video', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'livre', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichierlivre', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichier', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'fichiercour'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEc(): ?\App\Entity\Ec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEc', []);

        return parent::getEc();
    }

    /**
     * {@inheritDoc}
     */
    public function setEc(?\App\Entity\Ec $ec): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEc', [$ec]);

        return parent::setEc($ec);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichierSupport(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichierSupport', []);

        return parent::getFichierSupport();
    }

    /**
     * {@inheritDoc}
     */
    public function addFichierSupport(\App\Entity\FichierSupport $fichierSupport): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFichierSupport', [$fichierSupport]);

        return parent::addFichierSupport($fichierSupport);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFichierSupport(\App\Entity\FichierSupport $fichierSupport): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFichierSupport', [$fichierSupport]);

        return parent::removeFichierSupport($fichierSupport);
    }

    /**
     * {@inheritDoc}
     */
    public function getAudio(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAudio', []);

        return parent::getAudio();
    }

    /**
     * {@inheritDoc}
     */
    public function addAudio(\App\Entity\Audio $audio): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAudio', [$audio]);

        return parent::addAudio($audio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAudio(\App\Entity\Audio $audio): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAudio', [$audio]);

        return parent::removeAudio($audio);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function addVideo(\App\Entity\Video $video): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVideo', [$video]);

        return parent::addVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVideo(\App\Entity\Video $video): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVideo', [$video]);

        return parent::removeVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichier', []);

        return parent::getFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setFichier($fichier): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichier', [$fichier]);

        return parent::setFichier($fichier);
    }

    /**
     * {@inheritDoc}
     */
    public function setFichierCour(\Symfony\Component\HttpFoundation\File\File $fichiercour = NULL): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichierCour', [$fichiercour]);

        parent::setFichierCour($fichiercour);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichierCour(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichierCour', []);

        return parent::getFichierCour();
    }

    /**
     * {@inheritDoc}
     */
    public function getLivre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivre', []);

        return parent::getLivre();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivre($livre): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivre', [$livre]);

        return parent::setLivre($livre);
    }

    /**
     * {@inheritDoc}
     */
    public function setFichierlivre(\Symfony\Component\HttpFoundation\File\File $fichierlivre = NULL): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichierlivre', [$fichierlivre]);

        parent::setFichierlivre($fichierlivre);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichierlivre(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichierlivre', []);

        return parent::getFichierlivre();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
