<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9xlGIc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9xlGIc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN9xlGIc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN9xlGIc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN9xlGIc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N9xlGIc',
    'container.build_id' => '8bfa6d03',
    'container.build_time' => 1672783391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN9xlGIc');
